name: build-FSFW-Schulstick-ISO

on:
  schedule:
    - cron: "30 13 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up build prerequisites
      run: |
        sudo apt install live-build rsync pandoc
    - name: build this
      run: |
        sudo sh -xv scripts/build-live-system.sh FSFW-Schulstick
