name: build-FSFW-Schulstick-ISO

on:
  schedule:
    - cron: "30 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up build prerequisites
      run: |
        sudo apt install debootstrap rsync pandoc
        git clone https://salsa.debian.org/live-team/live-build.git
        cd live-build
        sudo make install
    - name: build this
      run: |
        pwd
        sudo bash -xv scripts/build-live-system.sh FSFW-Schulstick
    - name: publish ISO as artifact
      uses: actions/upload-artifact@v1
      with:
        name: iso-image
        path: iso-images
    - name: publish build log as well
      uses: actions/upload-artifact@v1
      with:
        name: build.log
        path: build_*.log
