name: build-FSFW-Schulstick-ISO

on:
  schedule:
    - cron: "15 14 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up build prerequisites
      run: |
        sudo apt install live-build rsync pandoc
    - name: build this
      run: |
        sudo bash -xv scripts/build-live-system.sh FSFW-Schulstick
    - name: publish ISO as artifact
      uses: actions/upload-artifact@v1
      with:
        name: iso-image
        path: iso-images
    - name: publish build log as well
      uses: actions/upload-artifact@v1
      with:
        name: build.log
        path: build_*.log
